### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by shinokada** [HcwXd/better-medium-stats#4]
Hi,

I noticed that the Summary and Stories are not working with the new Medium.

Is there any solutions to these?

![image](https://user-images.githubusercontent.com/147320/98893247-683ef800-24e5-11eb-9e00-1e3e8e8193a5.png)

![image](https://user-images.githubusercontent.com/147320/98893326-90c6f200-24e5-11eb-91f5-cfee08b7a341.png)

**Comment by shinokada** [comment]
It is working now.
I don't know why.

Thanks anyway.

**Comment by ali-kamalizade** [comment]
I had a similar issue:
- On the Medium stats page some charts did not work
- On my Medium profile page everything was fine
